### ISSUE TITLE
nrf-softdevice-gen broken

### ISSUE THREAD

**Issue by jacobrosenthal** [akiles/nrf-softdevice#24]
Fallout from  #1

moving the .cargo/config up means nrf-softdevice-gen is currently broken unless you pass an override --target or just comment out the target in .cargo/config

Mixing std and no_std in a single workspace is kind of a pain

You probably want to move it outside the other no_std stuff or the entire repo?

**Comment by Dirbaio** [comment]
True. That's the reason why `.cargo/config` was in `examples/`, but that means you can't build/run examples from the root so it isn't ideal either :( 

Not sure what to do.

Relevant issue: rust-lang/cargo#8112

**Comment by kuon** [comment]
One thing I often do is to create a Makefile to wrap language specific tools (rake, webpack, iex, cargo...). Then you just run `make build`, `make gen`... And you ensure correct environment in the tasks. Of course this is just a suggestion.
