### ISSUE TITLE
Data Length Extension negotiation

### ISSUE THREAD

**Issue by Dirbaio** [akiles/nrf-softdevice#5]
The BLE data length extension must be negotiated using `sd_ble_gap_data_length_update` and events `on_data_length_update_request`, `on_data_length_update`

Nordic's equivalent code is in `nrf_ble_gatt.c`

**Comment by Dirbaio** [comment]
The most user-friendly way to implement this I think would be:
- the desired data length should be specified in the Config struct when initializing the softdevice
- Automatically start the negotiation on connection, if current data length is less than desired. 

This way the user doesn't have to remember to manually start it.

**Comment by jacobrosenthal** [comment]
I presume you intended to move the 
evt.evt.gap_evt
